version: '3'
services:
  frontend:
    build: ./frontend
    image: "expense_analyzer/frontend"
    ports:
    - "8080:8080"
  api:
    build: ./api
    image: "expense_analyzer/api"
    ports:
    - 5000:80
    - 5001:443 
    volumes: 
      - /home/karol/certs/localhost.pfx:/cert/localhost.pfx
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=q
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/cert/localhost.pfx